[package]
name = "bump-into"
version = "0.4.2"
edition = "2018"
authors = ["Autumn <autumnontape@tutanota.com>"]
description = "a no_std bump allocator over an arbitrary region of memory"
license = "MIT OR Apache-2.0"
repository = "https://github.com/autumnontape/bump-into"
categories = ["no-std", "rust-patterns", "memory-management"]
readme = "README.md"
documentation = "https://docs.rs/bump-into"

[dependencies]
